force-app/main/default/objects/CATT_Request__c/CATT_Request__c.object-meta.xml
<CustomObject>
    <label>CATT Request</label>
    <nameField>
        <label>CATT Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CATT Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CATT_Request__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CATT Requests</relationshipLabel>
    <relationshipName>CATT_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CATT_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
            <value>
                <fullName>Waiting on Customer</fullName>
            </value>
            <value>
                <fullName>Waiting on Internal Resource</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Completed - Pending Success Story</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CATT_Request__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CattUtility.cls
/**
 * @File Name          : CattUtility.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 5/20/2020, 3:31:28 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    5/20/2020   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class CattUtility {
    public CattUtility() {

    }

    @AuraEnabled (cacheable=true)
    public static List<CATT_Request__c> getCattRequests(){
        return [select id, Name, Status__c, Subject__c, Account__r.name, Description__c from CATT_Request__c];
    }
}